spring.application.name=rent
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=Rent
info.add.description=Useful App
info.app.version=1.0.2

spring.security.user.name=greta
spring.security.user.password=1234
spring.main.initialization=true

management.endpoints.web.exposure.exclude=*
car.name=Mercedes
motor.type=6.3

server.port=7070

spring.datasource.url=jdbc:mysql://localhost:3306/rent
spring.datasource.username=root
spring.datasource.password=123456
spring.flyway.url = jdbc:mysql://localhost:3306/rent
spring.flyway.user = root
spring.flyway.password = 123456

